<a href="https://colab.research.google.com/github/Wise-Wizard/Artificial-Neural-Networks/blob/main/Copy_of_artificial_neural_network.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Artificial Neural Network

### Importing the libraries

In [32]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [33]:
tf.__version__

'2.12.0'

## Part 1 - Data Preprocessing

### Importing the dataset

In [34]:
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:, 3 : -1].values
y = dataset.iloc[:, -1].values

In [35]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [36]:
print(y)

[1 0 1 ... 1 1 0]


### Encoding categorical data

Label Encoding the "Gender" column

In [37]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[ : , 2 ] = le.fit_transform(X[ : , 2 ])

In [38]:
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


One Hot Encoding the "Geography" column

In [39]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder = 'passthrough')
X = np.array(ct.fit_transform(X))

In [40]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


### Splitting the dataset into the Training set and Test set

In [41]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y)

### Feature Scaling

In [42]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

## Part 2 - Building the ANN

### Initializing the ANN

In [43]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [44]:
ann.add(tf.keras.layers.Dense(units = 6, activation = 'relu'))

### Adding the second hidden layer

In [45]:
ann.add(tf.keras.layers.Dense(units = 6, activation = 'relu'))

### Adding the output layer

In [46]:
ann.add(tf.keras.layers.Dense(units = 1, activation = 'sigmoid'))

## Part 3 - Training the ANN

### Compiling the ANN

In [47]:
ann.compile(optimizer='adam', loss='binary_crossentropy', metrics='accuracy')

### Training the ANN on the Training set

In [51]:
ann.fit(X_train, y_train, batch_size = 80, epochs=10)

Epoch 1/10
94/94 [==============================] - 0s 2ms/step - loss: 0.3248 - accuracy: 0.8619
Epoch 2/10
94/94 [==============================] - 0s 2ms/step - loss: 0.3246 - accuracy: 0.8616
Epoch 3/10
94/94 [==============================] - 0s 2ms/step - loss: 0.3248 - accuracy: 0.8616
Epoch 4/10
94/94 [==============================] - 0s 2ms/step - loss: 0.3247 - accuracy: 0.8627
Epoch 5/10
94/94 [==============================] - 0s 2ms/step - loss: 0.3247 - accuracy: 0.8616
Epoch 6/10
94/94 [==============================] - 0s 2ms/step - loss: 0.3248 - accuracy: 0.8615
Epoch 7/10
94/94 [==============================] - 0s 2ms/step - loss: 0.3245 - accuracy: 0.8620
Epoch 8/10
94/94 [==============================] - 0s 2ms/step - loss: 0.3247 - accuracy: 0.8632
Epoch 9/10
94/94 [==============================] - 0s 2ms/step - loss: 0.3249 - accuracy: 0.8612
Epoch 10/10
94/94 [==============================] - 0s 2ms/step - loss: 0.3249 - accuracy: 0.8625


## Part 4 - Making the predictions and evaluating the model

### Predicting the result of a single observation

**Homework**

Use our ANN model to predict if the customer with the following informations will leave the bank: 

Geography: France

Credit Score: 600

Gender: Male

Age: 40 years old

Tenure: 3 years

Balance: \$ 60000

Number of Products: 2

Does this customer have a credit card? Yes

Is this customer an Active Member: Yes

Estimated Salary: \$ 50000

So, should we say goodbye to that customer?

In [52]:
print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) > 0.5)

1/1 [==============================] - 0s 23ms/step
[[False]]


### Predicting the Test set results

In [53]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

79/79 [==============================] - 0s 2ms/step
[[0 0]
 [0 0]
 [0 0]
 ...
 [1 1]
 [0 0]
 [0 0]]


### Making the Confusion Matrix

In [54]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1909   96]
 [ 239  256]]


0.866